// Generated by scripts/generate-media-formats.mjs.
package kr.threechan.photo;
final class MediaFormats {
    private static final java.util.Set<String> EXTENSIONS = new java.util.HashSet<>(java.util.Arrays.asList("jpg","jpeg","jpe","jfif","png","webp","heic","heif","hif","avif","avifs","tif","tiff","gif","bmp","dib","ico","psd","psb","jxl","jp2","j2k","jpf","jpx","jpc","pnm","ppm","pgm","pbm","dng","cr2","cr3","crw","nef","nrw","arw","srf","sr2","raf","rw2","rwl","orf","pef","x3f","3fr","fff","iiq","mef","mos","mrw","srw","raw","dcr","kdc","erf","k25","mdc","mp4","m4v","mov","mkv","webm","avi","mts","m2ts","ts","mpg","mpeg","mpe","vob","3gp","3g2","ogv","asf","wmv","mxf","flv"));
    static boolean supports(String name) {
        if (name == null || name.lastIndexOf('.') < 0) return false;
        return EXTENSIONS.contains(name.substring(name.lastIndexOf('.') + 1).toLowerCase(java.util.Locale.ROOT));
    }
}
